"""
publish_site.py
Deploy bridge (option B, issue #1): mirror this repo's built `sanantonio/`
folder into the austin-finance-data checkout — the single GitHub Pages source
for decodepolitics.org — commit it there, and push. After the push, the
section is live at decodepolitics.org/sanantonio/.

The `sanantonio/` folder in the Austin repo is GENERATED by this script.
Never hand-edit it; changes belong in this repo, then republish.

Guardrails:
  - refuses to publish from a dirty SA repo (the build being published must
    be committed, so every publish is reproducible from a sha) — --force to
    override
  - touches ONLY the `sanantonio/` subtree of the Austin repo (other dirty
    files there are left alone, loudly)
  - mirror semantics: files removed from the build are removed from deploy

Usage:
    python publish_site.py --dry-run     # show what would change
    python publish_site.py --no-push     # mirror + commit, no push
    python publish_site.py               # mirror + commit + push (LIVE)
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "sanantonio"
DEFAULT_AUSTIN = ROOT.parent / "austin-finance-data"


def sh(args, cwd):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"FATAL: {' '.join(args)} failed in {cwd}:\n{r.stderr}")
    return r.stdout.strip()


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--austin-repo", default=str(DEFAULT_AUSTIN))
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--no-push", action="store_true")
    p.add_argument("--force", action="store_true",
                   help="Publish even if this repo has uncommitted changes")
    args = p.parse_args()

    austin = Path(args.austin_repo)
    dst = austin / "sanantonio"
    if not SRC.is_dir():
        raise SystemExit(f"FATAL: build folder missing: {SRC}")
    if not (austin / ".git").exists() and not (austin / ".git").is_file():
        raise SystemExit(f"FATAL: not a git checkout: {austin}")

    sa_dirty = sh(["git", "status", "--porcelain"], ROOT)
    if sa_dirty and not args.force:
        raise SystemExit(
            "FATAL: this repo has uncommitted changes — commit the build first so\n"
            "the publish is reproducible from a sha (--force to override):\n" + sa_dirty)
    sha = sh(["git", "rev-parse", "--short", "HEAD"], ROOT)

    austin_dirty = sh(["git", "status", "--porcelain"], austin)
    if austin_dirty:
        outside = [ln for ln in austin_dirty.splitlines()
                   if "sanantonio/" not in ln]
        if outside:
            print("NOTE: austin repo has uncommitted changes OUTSIDE sanantonio/ —"
                  " they are left untouched:")
            for ln in outside[:10]:
                print("   ", ln)

    # ── mirror ────────────────────────────────────────────────────────────────
    src_files = {f.relative_to(SRC) for f in SRC.rglob("*") if f.is_file()}
    dst_files = {f.relative_to(dst) for f in dst.rglob("*") if f.is_file()} if dst.exists() else set()

    to_delete = sorted(dst_files - src_files)
    to_copy = sorted(rel for rel in src_files
                     if rel not in dst_files or not filecmp.cmp(SRC / rel, dst / rel, shallow=False))
    unchanged = len(src_files) - len(to_copy)

    print(f"[publish] {len(src_files)} built files -> {dst}")
    print(f"[publish] copy/update: {len(to_copy)}  delete: {len(to_delete)}  unchanged: {unchanged}")
    for rel in to_copy[:25]:
        print(f"    + {rel}")
    if len(to_copy) > 25:
        print(f"    + ... {len(to_copy) - 25} more")
    for rel in to_delete:
        print(f"    - {rel}")

    if args.dry_run:
        print("[publish] --dry-run: nothing written")
        return 0
    if not to_copy and not to_delete:
        print("[publish] nothing to publish")
        return 0

    for rel in to_copy:
        (dst / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SRC / rel, dst / rel)
    for rel in to_delete:
        (dst / rel).unlink()

    # ── commit + push (sanantonio/ subtree only) ──────────────────────────────
    sh(["git", "add", "-A", "--", "sanantonio/"], austin)
    staged = sh(["git", "diff", "--cached", "--name-only"], austin)
    if not staged:
        print("[publish] mirror produced no git changes")
        return 0
    sh(["git", "commit", "-m",
        f"Publish San Antonio section (generated from san-antonio-finance-data@{sha})\n\n"
        "Generated by publish_site.py — never hand-edit sanantonio/ here."], austin)
    print(f"[publish] committed in {austin.name}: {sh(['git', 'log', '-1', '--oneline'], austin)}")

    if args.no_push:
        print("[publish] --no-push: NOT pushed (not live yet)")
        return 0
    sh(["git", "push"], austin)
    print("[publish] pushed — decodepolitics.org/sanantonio/ will update with GitHub Pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
